#include <iostream> // Libreria estandar de c++
using namespace std; ///Esta función nos permite evitar poner std en cada línea de cogido, ya que esto abarca todo.
int main() //punto de partida para la ejecución del programa.
{
int pago,f=0;//DECLARAMOS NUESTROS VARIABLE INT (NUMERO ENTERO)Y DEFINICION DE VARIABLES.
int salario[pago],i;// SE DEFINE EL ARREGLO NUMERO Y SU TAMAÑO QUE CONTIENE 
float suma,prom;//DECLARAMOS NUESTROS VARIABLE FLOAT (FLOTANTE)Y DEFINICION DE VARIABLES.
{
system("color 3");// DEFINIMOS EL COLOR A UTILIZAR DE LAS LETRAS EN LA PANTALLA
cout<<"----ESTE PROGRAMA CALCULA EL PROMEDIO DE SALARAIOS E IMPRIME EL QUE ES MAS ALTO AL PROMEDIO----";//Mensaje en pantalla que muestra a usuario de que trata el programa.
cout<<"\n\nINTRODUCE LA CANTIDAD DE SALARIOS:";// SE LE PIDE AL USUARIO QUE INGRESE LA CANTIDAD DE SALARIOS.
cin>>pago;// GUARDA EL VALOR DE LA CANTIDAD DE pagos QUE INGRESO USUARIO.

for(int i=0;i<pago;i++)// UTILIZAMOS LA FUNCION FOR (I=0 PARA QUE EL CONTEO INICIE DESDE 0), EL VALOR DEL ELEMENTO VA AUMENTANTO CON i++(asignar posiscion). 
{
cout<<"\n\nINTRODUZCA LOS SALARIOS:";//SE LE PIDE AL USUARIO QUE INTRODUZCA EL VALOR DE LOS SALARIOS.
cin>>salario[i];// SE GUARDA EL VALOR DEL SALARIO.	
if(salario[i]>f)//SE UTILIZA CONDICIONAL --COMPARACION DE VARIABLES PARA SABER CUAL ES LA MAYOR DE TODAS.
{
f=salario[i];//SE GUARDA EL RESULTADO DE LA COMPARACION.	
}
}	

for (int i=0;i<pago;i++)//ciclo for (valor de inicio, valor final y tamaño de paso)
{
suma=suma+salario[i];//EN ESTA LINEA DE CODIGO SE REALIZA LA OPERACION ARITMETICA DONDE SE SUMAN TODOS LOS SALARIOS AGREGADOS POR EL USUARIO.
}
prom=suma/pago;//EN ESTA LINEA DE CODIGO SE REALIZA LA OPERACION ARITMETICA DONDE SE DIVIDE LA SUMA TOTAL DE LOS SALARIOS ENTRE LA CANTIDAD DE SALARIOS.
cout<<"\n\n EL PROMEDIO ES:"<<prom;// SE MUESTRA EN PANTALLA EL PROMEDIO.

cout<<"\n\nSALARIO MAYOR AL PROMEDIO:"<<"$"<<f;//SE MUESTRA EN PANTALLA A EL USUARIO EL SALARIO QUE ES MAYOR AL PROMEDIO.
}	
return 0;	//FINALIZACION DE PROGRAMA.
}